### ISSUE TITLE
Add bindings cache to store modified keybinding settings across sessions

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#101]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] User-defined keybindings are saved on pplication shutdown
- [ ] They are restored from the ``bindings-cache.json`` when the client starts
- [ ] Default bindings are provided and used when no bindings cache exists (or it's invalid)

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] TBD

### Personal Notes

Inspired by the WOW client's bindings cache and related APIs, e.g. https://wowpedia.fandom.com/wiki/API_SaveBindings
