### ISSUE TITLE
Convert global scripts to ES6 modules

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#102]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Remove the various "missing globals" warnings that are raised by ``eslint``
- [ ] Allow building a dependency graph automatically (via ``arcit`` or similar)

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] Convert all the files to proper ES6 modules
- [ ] Update the ``type`` entry in ``package.json``

### Personal Notes

I really dislike the JS module system, so this is TBD. I'll give it a try and see if the result is an improvement...

There's also the question of how addons should be handled/loaded.

Links:

* https://nodejs.org/api/esm.html
* https://nodejs.org/api/modules.html

**Comment by rdw-software** [comment]
This actually doesn't work, because electron uses Chromium's import inside the browser process. The result is that all the node modules and builtins won't be available. Also attempting to use import in the main thread crashes the application and I haven't found a way to get around that.

Considering the electron issue has been ignored for years, I don't see this as a practical task. Either a different design based on the global ``window`` object and Chromium's loading has to be devised, or perhaps I could experiment with NodeWebkit as it is said to be working there.

**Comment by rdw-software** [comment]
Set to waiting as in "waiting for electron to get it working". Whether that will happen remains to be seen...

**Comment by rdw-software** [comment]
How about using CommonJS modules instead? Will that at least work? Not sure if Electron has full support for them, particularly if Node integration is limited to the main thread...
