### ISSUE TITLE
Add support for rendering skeletal animations

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#106]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Meshes can be animated using skeletons (BJS provides APIs for this)
- [ ] Skeletons can be swapped on the fly
- [ ] Animations are handled via a high-level ``C_Animation API``

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] TBD
