### ISSUE TITLE
Add a popup window that allows players to respawn when they die

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#108]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Players can respawn after they die

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] Create ``RespawnWindow`` widget (or similar)
- [ ] On ``PLAYER_DIED`` event, show the window
- [ ] When clicked, send a ``REQUEST_RESPAWN_AFTER_DEATH`` request to the server
- [ ] On ``MAP_CHANGE`` event, hide the window (includes respawn)
- [ ] When ``ESC`` is pressed, toggle the window (only while the player is dead)
