### ISSUE TITLE
Update issue templates to use the latest version

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#109]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Remove GitHub's annoying message

![image](https://user-images.githubusercontent.com/16489133/128347309-defa3024-39cc-4cea-bb82-6b7814a64799.png)

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] Read the documentation at https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
- [ ] Update the issue template (PR also?)

### Personal Notes

Annoying busywork...

**Comment by rdw-software** [comment]
Obsolete, since I removed the template pending a do-over inspired by Node's interactive issues templates.
