### ISSUE TITLE
Implement a standardized banking UI for the accountwide item storage

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#110]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Players should be able to access the accountwide item storage via a specialized UI
- [ ] They must be able to deposit items in the storage
- [ ] They must be able to retrieve items from the storage
- [ ] They must be able to see the capacity and current fill rate
- [ ] Control should be implemented via drag & drop or ``SHIFT-RCLICK`` (customizable keybind)

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] TBD
