### ISSUE TITLE
Implement movement requests when clicking on terrain that isn't obstructed

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#113]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Pretty sure it can just be copy/pasted from an earlier prototype, as this was already working (IIRC)

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] Copy/paste previous implementation
- [ ] Refactor it maybe
- [ ] Tests and documentation
