### ISSUE TITLE
Implement basic UI for displaying player health and power bars

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#114]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] I've already done this as an addon, but it should likely be part of the default UI instead

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] Copy/paste the old implementation
- [ ] Possibly refactor it
