### ISSUE TITLE
Implement a basic version of Blizzard's Floating Combat Text

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#115]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Can display HIT damage or MISS
- [ ] Text is displayed near the affected unit
- [ ] Text can move in arbitrary directions, controlled by mathematical curves (injected with randomness)
- [ ] Can be disabled clientside
- [ ] Uses the server's combat log events to determine what to display
- [ ] Should be performant enough to not slow down FPS even if many numbers need to be displayed (particles or sprites? Needs benchmarking/API comparison to decide what's simpler)

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] TBD
