### ISSUE TITLE
Implement attack requests when clicking on hostile creatures

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#117]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Copy/paste from the previous prototypes

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ]  Copy/paste previous implementation
- [ ] Refactor it maybe
- [ ] Tests and documentation
