### ISSUE TITLE
Implement camera presets that can be swapped in

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#118]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Camera presets can be registered using a set of standardized settings
- [ ] Can swap between all registered presets, using the ``C_Camera`` API
- [ ] Swapping changes the way the scene is rendered (by setting the camera as active and applying the settings to it)
- [ ] Presets exist for the orbital debug camera, as well as the free debug camera

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] TBD

### Personal Notes

This could later be extended to render a realtime minimap view or similar.
