### ISSUE TITLE
Add option to automatically remove unused resources after a set timeout period

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#119]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Unused resources can be freed when no longer needed
- [ ] This can be configured (toggled) via the ``C_Resources`` API
- [ ] The timeout can also be configured

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] TBD
