### ISSUE TITLE
Add asynchronous version of the resource APIs

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#120]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [ ] Resources can be loaded asynchronously in the same way as the 
- [ ] ``async`` and ``await`` should be used (to eliminate the need for callbacks)

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [ ] Create ``async`` versions of the ``C_Resources`` API
- [ ] Create ``async`` versions of the ``C_FileSystem`` API
