### ISSUE TITLE
Add script to run static analysis tools locally (eslint?)

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#49]
Goals:

- [x] A framework like ``eslint`` should be added as development dependency
- [x] Its configuration should be stored in a separate file, ``linter-config.json`` (or similar)
- [x] The process should be made available locally via a NPM script, ``npm check``
