### ISSUE TITLE
Set up a new GitHub Actions workflow to run a static analysis tool on pull requests

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#50]
Goals:

- [x] The workflow should execute ``eslint`` or similar (TBD) in the exact same configuration as ``npm test`` (see https://github.com/RevivalEngine/WebClient/issues/49)
- [x] When the workflow fails, this fact should become visible in the PR itself somehow (ideally via GitHub and not a bot posting a comment to reduce clutter)
- [x] Releases should be unaffected (separate workflow) as otherwise the build workflow will become even more complex
