### ISSUE TITLE
Set up a new GitHub Actions workflow to run a format check on pull requests

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#56]
Goals:

- [x] Consistent formatting across all files should be enforced
- [x] Should use the same formatter config that ``npm run format`` utilizes
- [x] Violations should be reported in the PR itself
- [x] Should not affect the build pipeline (to keep workflows simple)
