### ISSUE TITLE
Add script to run code formatting locally (prettier?)

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#57]
Goals:

- [x] A framework like ``prettier`` should be added as development dependency
- [x] Its configuration should be stored in a separate file, ``formatter-config.json`` (or similar)
- [x] The process should be made available locally via a NPM script, ``npm run format``

**Comment by rdw-software** [comment]
Can't we misappropriate ``eslint`` for this? It's already complaining about formatting anyway.

**Comment by rdw-software** [comment]
Looks like the ``eslint`` formatter is not an actual code formatter, but rather plugins designated to formatting the linting results. Oh well.

**Comment by rdw-software** [comment]
Since ``prettier`` uses a custom config format for the "blacklisted files" config, similar to ``.gitignore``, I had to break with the naming scheme a bit here. Unfortunate, but alas, it hopefully won't make understanding the config any more difficult.
