### ISSUE TITLE
Implement basic prototype of the AddonOptionsFrame

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#65]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [x] Users can manage the loading of installed addons via a convenient UI that's accessible from the main menu

### Roadmap

Please list the exact steps needed to implement the change here in as much detail as you see fit:

- [x] Create UI prototype
- [x] Create ScrollFrame widget (for the list of installed addons)
- [x] Create checkboxes for each of the installed (recognized) addons
- [x] Create a button to reload the UI (as disabling addons requires a restart currently)
- [x] When a previously-disabled addon is enabled (``ADDON_LOADED`` event), update the checkbox state
- [x] When a previously-disabled addon is enabled, it is loaded (on demand)
- [x] When a previously-enabled addon is disabled, it is NOT unloaded immediately, but instead flagged as ``disableOnShutdown`` (or similar)
- [x] When a previously-enabled addon is disabled, the reload UI button is highlighted
- [x] Update templates (CSS) to make the UI visually consistent with the default interface
- [x] Implement any missing functionality in the ``C_Addons`` API for the menu to be usable
