### ISSUE TITLE
Add a way to close UI windows by simply pressing ESC

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#69]
**TODO: This issue conflates several concepts and needs some untangling in order to implement them individually**

---

Goals:

- [ ] Pressing ESC should close the most prominent window/closable frame
- [ ] Pressing ESC while an input (``EditBox``, ``TextArea`` etc.) is active should NOT close the window (to avoid losing data)
- [ ] By default, frames should NOT be closable (WOW UI default behaviour)
- [ ] When multiple closable windows are visible and the ESC key is pressed, the one that ranks highest in the widget hierarchy should be closed

Roadmap:

- [ ] Actually add a proper system for layers and the widget hierarchy (separate issue; blocks this one!)
  - [ ] Add API to compute the CSS ``z-index`` based on strata and level (strata is a layer, and the level corresponds to the CSS ``z-index`` offset)
  - [ ] Add an API to dynamically adjust strata, level, and ``z-index``
  - [ ] Add default layers (WOW API)
- [ ] Introduce a way to make an existing window closable (``Window.setClosable(true)``?)
- [ ] Also add ``Window.isClosable()``, for consistency mainly
- [ ] Introduce the ``C_Widget`` API to deal with UI concerns such as these (again...)
- [ ] Maintain a list of closable windows in the ``C_Widget`` namespace, sorted by their frame strata and then level
- [ ] Modify the input handler (in the ``C_WebGL`` namespace) to close the "highest" closable, visible window
- [ ] Streamline input propagation and keyboard event handling (separate issue!)
  - [ ] Introduce ``Frame.enableKeyboard()`` to toggle this behaviour (OFF = not closing on escape)
  - [ ] 
- [ ] 

Resources (needs sorting out):

* https://wowwiki-archive.fandom.com/wiki/Make_Frames_Closable_With_the_%22Esc%22_Key
* https://wow.gamepedia.com/Layer
* https://wowpedia.fandom.com/wiki/Frame_Strata
* https://wowpedia.fandom.com/wiki/Frame_Strata
* https://wowpedia.fandom.com/wiki/API_Frame_GetPropagateKeyboardInput
* https://wowpedia.fandom.com/wiki/API_Frame_EnableKeyboard
* https://wowpedia.fandom.com/wiki/UIHANDLER_OnKeyDown
* https://wowpedia.fandom.com/wiki/UIHANDLER_OnKeyUp
