### ISSUE TITLE
Store settings in a JSON file so that they can be managed (and validated) properly

### ISSUE THREAD

**Issue by rdw-software** [rdw-archive/WebClient#99]
### Goals

Please describe briefly the intended purpose of the change and the rationale behind it:

- [x] The various eslint warnings about globals should be eliminated, without having to add the individual settings (global constants) to its configuration file
- [x] Settings are instead stored in a single json file
- [x] One of these exists for both user and default settings
- [x] If the user-settings (cache) file does not exist, the defaults are used
- [x] On load, the cache is validated (schema) and invalid settings are discarded with a warning (restore defaults)
- [x] On application shutdown, the cache is saved to disk
- [ ] ~~The cache is excluded from git~~ -> Later (see comment)

### Roadmap

Please list the exact steps needed to implement the change here, in as much detail as you see fit:

- [x] Add a wrapper for the ``Joi`` framework, similar to other libraries (i.e., a global ``JOI`` is exposed)
- [x] Define schema for the settings file (using the ``JOI`` API)
- [x] Extend ``C_Settings`` API to allow calling the validation routines with a schema
- [x] Extend ``C_Validation`` API to validate the files using a given schema
- [x] Convert the existing settings to their respective JSON format
- [x] Update initialization routine to load settings from that JSON file (instead of using the globals directly)
- [x] Extend ``C_Settings`` API to allow accessing the configuration (JSON objects) directly from cache
- [x] Ensure all references to the new settings are updated to use the ``C_Settings`` API
- [x] Remove the old JS files that have then become obsolete

### Personal Notes

Split off from https://github.com/RevivalEngine/WebClient/issues/96 as this task is complex enough to warrant its own issue.

**Comment by rdw-software** [comment]
I don't like the current (WIP) design of having tons of configuration files and schema definitions. It might be simpler to just have a simple ``default-settings.json`` that is loaded initially, and persist user settings to ``settings-cache.json``, similar to macros and the addon configuration.

Then, on subsequent startups, the cache could be restored (if it exists), or any missing settings taken from the default configuration. One drawback is that the file might become huge and difficult to parse; however, many smaller files are also difficult to navigate and so I'd assume that settings need to be exposed through UI anyway.

I'll implement this and see if it works out. Can always roll back the changes and try a different design...

**Comment by rdw-software** [comment]
>  The cache is excluded from git

This part needs a better design, as currently the defaults are tracked by git and any changes can the not be ignored. Some settings already have a separate cache for default (tracked, never changes from user actions) and user settings, but some don't. That inconsistency will have to be resolved separately, but so far I've been too lazy.
